In [197]:
import pandas as pd
import numpy as np
import matplotlib.pyplot
import seaborn as sns

In [198]:
df= pd.read_csv("/Users/abiodun/Downloads/auto.csv")

In [199]:
df

,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [200]:
headers = ["symbol","normali-loss","make","fuel","aspirnt", "doors","body",
         "wheels","eng-location","wheel-base", "length","width","height","curb-weight","engine-type",
         "no-cylinders", "engine-size","fuel-system","bore","stroke","compresn-ratio","horse-power",
         "rpm","c-mpg","h-mpg","price"]

In [201]:
df.columns = headers

In [202]:
df

,symbol,normali-loss,make,fuel,aspirnt,doors,body,wheels,eng-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compresn-ratio,horse-power,rpm,c-mpg,h-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [203]:
df.describe()

,symbol,wheel-base,length,width,height,curb-weight,engine-size,compresn-ratio,c-mpg,h-mpg
count,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000,204.000000
mean,0.823529,98.806373,174.075000,65.916667,53.749020,2555.602941,126.892157,10.148137,25.240196,30.769608
std,1.239035,5.994144,12.362123,2.146716,2.424901,521.960820,41.744569,3.981000,6.551513,6.898337
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.075000,52.000000,2145.000000,97.000000,8.575000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,119.500000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.200000,66.900000,55.500000,2939.250000,142.000000,9.400000,30.000000,34.500000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [204]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   symbol          204 non-null    int64
 1   normali-loss    204 non-null    object
 2   make            204 non-null    object
 3   fuel            204 non-null    object
 4   aspirnt         204 non-null    object
 5   doors           204 non-null    object
 6   body            204 non-null    object
 7   wheels          204 non-null    object
 8   eng-location    204 non-null    object
 9   wheel-base      204 non-null    float64
 10  length          204 non-null    float64
 11  width           204 non-null    float64
 12  height          204 non-null    float64
 13  curb-weight     204 non-null    int64
 14  engine-type     204 non-null    object
 15  no-cylinders    204 non-null    object
 16  engine-size     204 non-null    int64
 17  fuel-system     204 non-null    object
 18  bore            204 non-null    object
 19  stroke          204 non-null    object
 20  compresn-ratio  204 non-null    float64
 21  horse-power     204 non-null    object
 22  rpm             204 non-null    object
 23  c-mpg           204 non-null    int64
 24  h-mpg           204 non-null    int64
 25  price           204 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.6+ KB

In [205]:
df.head(7)

,symbol,normali-loss,make,fuel,aspirnt,doors,body,wheels,eng-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compresn-ratio,horse-power,rpm,c-mpg,h-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
5,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
6,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920

In [206]:
df.tail()

,symbol,normali-loss,make,fuel,aspirnt,doors,body,wheels,eng-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compresn-ratio,horse-power,rpm,c-mpg,h-mpg,price
199,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [207]:
df.replace('?',np.NaN, inplace = True)

In [208]:
df

,symbol,normali-loss,make,fuel,aspirnt,doors,body,wheels,eng-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compresn-ratio,horse-power,rpm,c-mpg,h-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [209]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   symbol          204 non-null    int64
 1   normali-loss    164 non-null    object
 2   make            204 non-null    object
 3   fuel            204 non-null    object
 4   aspirnt         204 non-null    object
 5   doors           202 non-null    object
 6   body            204 non-null    object
 7   wheels          204 non-null    object
 8   eng-location    204 non-null    object
 9   wheel-base      204 non-null    float64
 10  length          204 non-null    float64
 11  width           204 non-null    float64
 12  height          204 non-null    float64
 13  curb-weight     204 non-null    int64
 14  engine-type     204 non-null    object
 15  no-cylinders    204 non-null    object
 16  engine-size     204 non-null    int64
 17  fuel-system     204 non-null    object
 18  bore            200 non-null    object
 19  stroke          200 non-null    object
 20  compresn-ratio  204 non-null    float64
 21  horse-power     202 non-null    object
 22  rpm             202 non-null    object
 23  c-mpg           204 non-null    int64
 24  h-mpg           204 non-null    int64
 25  price           200 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.6+ KB

In [210]:
df.dropna(subset = 'price', axis = 0, inplace = True)

In [211]:
df

,symbol,normali-loss,make,fuel,aspirnt,doors,body,wheels,eng-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compresn-ratio,horse-power,rpm,c-mpg,h-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
202,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
203,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [212]:
rfm_mean = df["rpm"].astype("float").mean(axis = 0)
df["rpm"].replace(np.NaN,rfm_mean, inplace = True)

In [213]:
bore_mean = df["bore"].astype("float").mean(axis = 0)
df["bore"].replace(np.NaN,bore_mean, inplace = True)

In [214]:
stroke_mean = df["stroke"].astype("float").mean(axis = 0)
df["stroke"].replace(np.NaN,stroke_mean, inplace = True)

In [215]:
horse_mean = df["horse-power"].astype("float").mean(axis = 0)
df["horse-power"].replace(np.NaN,horse_mean, inplace = True)

In [216]:
norm_mean = df["normali-loss"].astype("float").mean(axis = 0)
df["normali-loss"].replace(np.NaN,norm_mean, inplace = True)

In [217]:
df.isnull().sum()

symbol            0
normali-loss      0
make              0
fuel              0
aspirnt           0
doors             2
body              0
wheels            0
eng-location      0
wheel-base        0
length            0
width             0
height            0
curb-weight       0
engine-type       0
no-cylinders      0
engine-size       0
fuel-system       0
bore              0
stroke            0
compresn-ratio    0
horse-power       0
rpm               0
c-mpg             0
h-mpg             0
price             0
dtype: int64

In [218]:
df['doors'].value_counts()

four    113
two      85
Name: doors, dtype: int64

In [219]:
df['doors'].replace(np.NaN,'four', inplace = True)

In [220]:
df.isnull().sum()

symbol            0
normali-loss      0
make              0
fuel              0
aspirnt           0
doors             0
body              0
wheels            0
eng-location      0
wheel-base        0
length            0
width             0
height            0
curb-weight       0
engine-type       0
no-cylinders      0
engine-size       0
fuel-system       0
bore              0
stroke            0
compresn-ratio    0
horse-power       0
rpm               0
c-mpg             0
h-mpg             0
price             0
dtype: int64

In [221]:
df.dtypes

symbol              int64
normali-loss       object
make               object
fuel               object
aspirnt            object
doors              object
body               object
wheels             object
eng-location       object
wheel-base        float64
length            float64
width             float64
height            float64
curb-weight         int64
engine-type        object
no-cylinders       object
engine-size         int64
fuel-system        object
bore               object
stroke             object
compresn-ratio    float64
horse-power        object
rpm                object
c-mpg               int64
h-mpg               int64
price              object
dtype: object

In [222]:
df['normali-loss'] = df['normali-loss'].astype("float")
df['price'] = df['price'].astype("float")
df[['rpm','horse-power','stroke','bore']] = df[['price','horse-power','stroke','bore']].astype("float")

In [223]:
df.dtypes

symbol              int64
normali-loss      float64
make               object
fuel               object
aspirnt            object
doors              object
body               object
wheels             object
eng-location       object
wheel-base        float64
length            float64
width             float64
height            float64
curb-weight         int64
engine-type        object
no-cylinders       object
engine-size         int64
fuel-system        object
bore              float64
stroke            float64
compresn-ratio    float64
horse-power       float64
rpm               float64
c-mpg               int64
h-mpg               int64
price             float64
dtype: object

In [224]:
df

,symbol,normali-loss,make,fuel,aspirnt,doors,body,wheels,eng-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compresn-ratio,horse-power,rpm,c-mpg,h-mpg,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,16500.0,21,27,16500.0
1,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,16500.0,19,26,16500.0
2,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,13950.0,24,30,13950.0
3,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,17450.0,18,22,17450.0
4,2,122.0,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110.0,15250.0,19,25,15250.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,16845.0,23,28,16845.0
200,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,19045.0,19,25,19045.0
201,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,21485.0,18,23,21485.0
202,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,22470.0,26,27,22470.0
203,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,22625.0,19,25,22625.0

In [225]:
df['c-mpg']=235/df['c-mpg']

In [226]:
df['h-mpg']=235/df['h-mpg']

In [227]:
df.rename(columns= {'c-mpg':'city-l/km'}, inplace = True)
df.rename(columns= {'h-mpg':'high_way - l/km'}, inplace = True)

In [231]:
df

,symbol,normali-loss,make,fuel,aspirnt,doors,body,wheels,eng-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compresn-ratio,horse-power,rpm,city-l/km,high_way - l/km,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,16500.0,11.190476,8.703704,16500.0
1,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,16500.0,12.368421,9.038462,16500.0
2,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,13950.0,9.791667,7.833333,13950.0
3,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,17450.0,13.055556,10.681818,17450.0
4,2,122.0,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110.0,15250.0,12.368421,9.400000,15250.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,16845.0,10.217391,8.392857,16845.0
200,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,19045.0,12.368421,9.400000,19045.0
201,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,21485.0,13.055556,10.217391,21485.0
202,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,22470.0,9.038462,8.703704,22470.0
203,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,22625.0,12.368421,9.400000,22625.0

In [232]:
df.reset_index(drop = True)

,symbol,normali-loss,make,fuel,aspirnt,doors,body,wheels,eng-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compresn-ratio,horse-power,rpm,city-l/km,high_way - l/km,price
0,3,122.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,16500.0,11.190476,8.703704,16500.0
1,1,122.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,16500.0,12.368421,9.038462,16500.0
2,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,13950.0,9.791667,7.833333,13950.0
3,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,17450.0,13.055556,10.681818,17450.0
4,2,122.0,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110.0,15250.0,12.368421,9.400000,15250.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,16845.0,10.217391,8.392857,16845.0
196,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,19045.0,12.368421,9.400000,19045.0
197,-1,95.0,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,21485.0,13.055556,10.217391,21485.0
198,-1,95.0,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,22470.0,9.038462,8.703704,22470.0
199,-1,95.0,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,22625.0,12.368421,9.400000,22625.0

In [233]:
df.to_csv("/Users/abiodun/Downloads/portfolio1.csv")